In [1]:
import numpy as np


In [2]:
my_list=list(range(10))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
array1=np.array(my_list)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
multi_list=[[1,2,3],[4,5,6]]
multi_list

[[1, 2, 3], [4, 5, 6]]

In [6]:
array2=np.array(multi_list)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(array2)

[[1 2 3]
 [4 5 6]]


In [8]:
array2.ndim

2

In [9]:
array1.ndim

1

In [10]:
array1.shape

(10,)

In [15]:
array2.shape

(2, 3)

In [22]:
array3 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]
array3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [23]:
array_multi=np.array(array3)
array_multi

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
array_multi.ndim


3

In [30]:
array_multi.shape

(3, 2, 2)

# DATA TYPES

In [34]:
array4=np.array(list(range(10)))
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.array(list(range(10)),dtype='float64')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
array5=np.array(list(range(10)),dtype='int32')
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
array6=array4.astype(np.float64)
array6

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
array7=np.array([3.5,-1.5,-2.5,0.5,12.5,10.0])
array7


array([ 3.5, -1.5, -2.5,  0.5, 12.5, 10. ])

In [42]:
array8=array7.astype(np.int64)
array8

array([ 3, -1, -2,  0, 12, 10], dtype=int64)

In [45]:
num_string=np.array(array8,dtype=np.string_)
num_string

array([b'3', b'-1', b'-2', b'0', b'12', b'10'], dtype='|S21')

In [46]:
num_array=np.array(array8,dtype=np.int32)
num_array


array([ 3, -1, -2,  0, 12, 10])

In [48]:
num_float=np.array(array8,dtype=np.float32)
num_float

array([ 3., -1., -2.,  0., 12., 10.], dtype=float32)